Repository zowe/zlux-file-explorer, pull requests merged in 2022-10, with the labels that each got.

#171 Add event to send FT nodes network responses
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/components/filebrowsermvs/filebrowsermvs.component.html
  src/app/components/filebrowsermvs/filebrowsermvs.component.ts
  src/app/components/filebrowseruss/filebrowseruss.component.html
  src/app/components/filebrowseruss/filebrowseruss.component.ts
  src/app/components/zlux-file-tree/zlux-file-tree.component.html
  src/app/components/zlux-file-tree/zlux-file-tree.component.ts
Labels: size/S

#172 Updated README.md
  README.md
Labels: size/XS

#174 add the dataset name in the search bar when opening in new tab
  src/app/components/filebrowsermvs/filebrowsermvs.component.ts
  src/app/components/zlux-file-tree/zlux-file-tree.component.ts
Labels: size/XS

#175 fixing bug where when opening DIrectory using URL always opens the r…
  src/app/components/filebrowseruss/filebrowseruss.component.ts
Labels: size/XS

#176 Fix open new tab
  CHANGELOG.md
  src/app/components/filebrowseruss/filebrowseruss.component.ts
Labels: size/XS

#169 adding the option to copy the link to the Dataset and uSS files
  CHANGELOG.md
  src/app/components/filebrowsermvs/filebrowsermvs.component.ts
  src/app/components/filebrowseruss/filebrowseruss.component.ts
  src/app/components/zlux-file-tree/zlux-file-tree.component.ts
Labels: size/M

#170 Dataset creation UI in File-tree
  package-lock.json
  src/app/components/create-dataset-modal/create-dataset-modal.component.html
  src/app/components/create-dataset-modal/create-dataset-modal.component.scss
  src/app/components/create-dataset-modal/create-dataset-modal.component.ts
  src/app/components/filebrowsermvs/filebrowsermvs.component.css
  src/app/components/filebrowsermvs/filebrowsermvs.component.html
  src/app/components/filebrowsermvs/filebrowsermvs.component.ts
  src/app/components/zlux-file-tree/zlux-file-tree.component.ts
  src/app/services/dataset.crud.service.ts
Labels: size/XL
